### ISSUE TITLE
Ticker-update frequency too high.

### ISSUE THREAD

**Issue by bracklanna** [nearengine/btcbar#14]
App updates all tickers ever 10 seconds. 
At least some tickers (e.g. WinkDex) request that API hits are limited to no more than once per 60 seconds -- and they may block apps that disrespect it.

Suggest changing the default rate to 60 seconds. 

If someone needs to see an exchange rate in real-time (e.g. traders) they would probably be using a separate browser window or dedicated app for that.

**Comment by nearengine** [comment]
I think this is reasonable, especially now that the movement has slowed down quite a bit. I need to get a fresh release out this week to fix the Huobi ticker, so I'll make this tweak as well.

**Comment by nearengine** [comment]
This has been updated, will get a 2.3 release out asap.
