### ISSUE TITLE
Minor: digits cut off when app first launches.

### ISSUE THREAD

**Issue by bracklanna** [nearengine/btcbar#15]
Under OS X 10.10.5, when first launching BTCBar, the $XXX amount is slightly cut-off (does not display fully.) This occurs regardless of which exchange is selected.

![screen shot 2015-12-11 at 12 23 46 pm](https://cloud.githubusercontent.com/assets/16140600/11754779/67d2caf8-a002-11e5-93a6-4b977a5223fc.JPG)

This resolves itself after the first round of updates, i.e. after about 10 seconds. But it might be nice to fix this to keep the app looking polished.
![screen shot 2015-12-11 at 12 24 03 pm](https://cloud.githubusercontent.com/assets/16140600/11754783/72db1c7a-a002-11e5-9eb0-f4cc124a949d.JPG)

**Comment by nearengine** [comment]
Thanks for the report, looks like OS X deprecated a bunch of the status item API in 10.10, updating the code seems to fix this issue. Getting a 2.3.0 release out for this asap.
